### ISSUE TITLE
보고싶은데 어떡하죠ㅠ

### ISSUE THREAD

**Issue by eunjng5474** [MalangCowFarm/Algo_Yejin#8]
https://github.com/MalangCowFarm/Algo_Yejin/blob/8c8a82a4757970e2add22063b019daebebe7a48b/week10/%EC%8A%A4%ED%84%B0%EB%94%94%EC%9B%90%EB%93%A4%EC%97%90%EA%B2%8C.txt#L2

**Comment by yelunar** [comment]
이번주 많이 봐서 해결 완료 ^___^
