### ISSUE TITLE
i 값에 따라 col값이 달라지는 이유 설명해줘..!

### ISSUE THREAD

**Issue by eunjng5474** [MalangCowFarm/Algo_Yejin#9]
https://github.com/MalangCowFarm/Algo_Yejin/blob/9fdabd2bb2206d02f624be0f91af0da36e20617b/week12/%EC%82%AC%EB%8B%A4%EB%A6%AC%EC%A1%B0%EC%9E%91.py#L38

**Comment by yelunar** [comment]
햇따
